<a href="https://colab.research.google.com/github/hillk055/Football-DS/blob/main/Copy_of_DS_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
import os
import pandas as pd


df = pd.read_csv('fifa_world_cup_2026_player_performance.csv')

df.info() # Check data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [ ]:
df.head() # check for metadata or secondary headers

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,RB Salzburg,4384884,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,72,0,0,0,0,0.00,0.00,0,15,26,0.59,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,4,0.83,0,1,0,0,7.8,0.7,26.5,13,23,81.9,5.6,50.9,3.3,48.2,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,Chelsea,4918927,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,90,0,0,0,0,0.01,0.00,1,35,40,0.89,1,0,1,0,0,1,3,1,2,0,2,5,0,1,0,0,0,0,0.00,0,0,0,0,10.4,1.1,29.0,19,17,85.5,5.7,55.9,37.9,29.4,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,AIK,125015698,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,73,1,0,2,0,0.08,0.07,2,72,85,0.85,0,0,3,0,1,1,0,0,1,2,4,2,0,0,0,0,0,0,0.00,0,0,0,0,8.8,1.3,33.7,30,19,88.8,8.3,82.9,79.8,78.6,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,PSV Eindhoven,11805512,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,80,1,1,5,2,0.00,0.21,0,12,19,0.67,1,0,0,0,1,1,1,0,3,0,1,3,0,1,0,0,0,0,0.00,0,0,0,0,9.6,1.0,32.1,26,19,89.2,6.9,67.5,47.3,6.9,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,Juventus,13325174,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,79,0,0,1,0,0.00,0.00,1,33,44,0.76,2,1,0,0,1,3,0,2,1,2,4,6,0,0,0,0,0,0,0.00,0,0,0,0,7.5,0.7,30.5,23,18,73.6,5.7,55.4,33.0,75.6,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [ ]:
df.tail() # check for any total columns that shouldn't be there

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,Pohang Steelers,2038987,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,62.9,0.0,0.0,18.9,40.2,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,Bunyodkor,18303109,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,79.5,0.0,3.1,28.8,37.6,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,Al-Duhail,9162130,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,69.7,0.0,2.2,64.8,59.0,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,Kawasaki Frontale,47033556,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.74,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,67.8,0.0,2.4,14.5,99.0,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,Ulsan HD,39256189,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,81.4,0.0,0.0,11.4,99.0,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
df.describe()

,age,jersey_number,height_cm,weight_kg,market_value_eur,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
count,54600.000000,54600.000000,54600.000000,54600.000000,5.460000e+04,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000
mean,26.296484,13.500000,181.654341,75.754853,2.008445e+07,1.330476,1.330476,36.199817,0.055385,0.052363,0.447051,0.048425,0.016112,0.017742,0.471832,15.470092,19.177308,0.808440,0.600293,0.162949,0.447784,0.018535,0.802656,0.627271,0.808681,0.226612,0.745256,0.362985,1.388571,2.465220,0.416886,0.323223,0.097912,0.005604,0.086905,0.121282,0.026274,0.026245,0.009176,0.048645,0.003333,3.996504,0.462372,18.645636,10.036502,8.849011,81.893535,3.634700,36.828995,44.716636,52.733712,2.850165,60.318379,46.135778,63.750396,55.572154,0.643993,0.607601,272.300311,0.030659,3.634046
std,4.067519,7.500069,6.277792,3.951481,2.718866e+07,1.147814,1.147814,36.419755,0.251900,0.239021,0.947155,0.244501,0.074648,0.074896,0.936476,18.747632,22.623857,0.074286,1.154876,0.497236,0.863716,0.137432,1.343731,1.125812,1.534296,0.558672,1.171042,0.713418,2.017851,3.643392,0.771273,0.653396,0.297198,0.074653,0.316943,0.701090,0.135945,0.207966,0.095351,0.330748,0.057639,4.023194,0.475044,16.016266,10.581358,9.390937,10.771734,3.155846,31.072667,24.870780,23.903033,4.228436,20.234988,22.424337,19.860028,13.661343,1.093781,0.931527,116.806184,0.206520,3.163411
min,17.000000,1.000000,163.000000,65.000000,5.288220e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.000000,1.000000,5.000000,0.000000,15.000000,5.000000,25.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,7.000000,177.000000,73.000000,4.444778e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.760000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,74.600000,0.000000,0.700000,25.675000,33.100000,0.000000,43.700000,29.800000,46.500000,46.400000,0.000000,0.000000,184.000000,0.000000,0.000000
50%,26.000000,13.500000,182.000000,76.000000,1.027111e+07,1.000000,1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,11.000000,0.820000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.300000,29.900000,6.000000,6.000000,82.600000,5.500000,54.100000,41.600000,49.900000,1.100000,57.000000,40.500000,61.100000,55.000000,0.000000,0.000000,268.000000,0.000000,5.400000
75%,29.000000,20.000000,186.000000,78.000000,2.342013e+07,2.000000,2.000000,75.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,27.000000,33.000000,0.860000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,2.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.900000,0.900000,32.700000,20.000000,17.000000,90.000000,6.400000,64.100000,60.800000,71.300000,4.000000,75.100000,59.000000,78.900000,63.900000,1.000000,1.000000,359.000000,0.000000,6.400000
max,39.000000,26.000000,200.000000,87.000000,2.000000e+08,7.000000,7.000000,90.000000,4.000000,3.000000,11.000000,5.000000,2.310000,2.200000,8.000000,97.000000,100.000000,0.970000,10.000000,6.000000,8.000000,2.000000,8.000000,7.000000,12.000000,4.000000,7.000000,5.000000,12.000000,23.000000,5.000000,4.000000,1.000000,1.000000,4.000000,11.000000,1.000000,3.000000,1.000000,7.000000,1.000000,14.000000,2.000000,37.000000,44.000000,40.000000,99.000000,9.400000,97.700000,99.000000,99.000000,37.000000,99.000000,99.000000,99.000000,99.000000,10.000000,8.000000,615.000000,4.000000,9.500000